-- DEVELOPMENT ONLY: deletes the tables (and ALL their data) so this file can be run again.
DROP TABLE IF EXISTS comments, likes, user_books, editions, works, users;

CREATE TABLE users(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        TEXT NOT NULL UNIQUE,
    email           TEXT NOT NULL UNIQUE,
    password_hash   TEXT NOT NULL,
    display_name    TEXT,
    bio             TEXT,
    about_me        TEXT,
    favorite_quote  TEXT,
    favorite_things TEXT,
    location        TEXT,
    avatar_url      TEXT,
    instagram_url   TEXT,
    tiktok_url      TEXT,
    reading_goal    SMALLINT CHECK (reading_goal BETWEEN 1 AND 365),
    reader_type     TEXT CHECK (reader_type IN ('first-time', 'casual', 'avid')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now() 
);

CREATE TABLE works (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                TEXT NOT NULL,
    author               TEXT NOT NULL,
    description          TEXT,
    cover_image          TEXT,
    first_published_year SMALLINT,
    open_library_key     TEXT UNIQUE,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE editions (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_id          INTEGER NOT NULL REFERENCES works (id) ON DELETE CASCADE,
    title            TEXT NOT NULL,
    language         TEXT,
    isbn_13          TEXT UNIQUE CHECK (isbn_13 ~ '^[0-9]{13}$'),
    publisher        TEXT,
    published_year   SMALLINT,
    page_count       SMALLINT CHECK (page_count > 0),
    cover_image      TEXT,
    open_library_key TEXT UNIQUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE user_books (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    work_id         INTEGER NOT NULL REFERENCES works (id) ON DELETE RESTRICT,
    edition_id      INTEGER REFERENCES editions (id) ON DELETE SET NULL,
    status          TEXT NOT NULL DEFAULT 'reading'
                    CHECK (status IN ('want-to-read', 'reading', 'finished')),
    progress        SMALLINT NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),
    current_page    INTEGER CHECK (current_page >= 0),
    total_pages     INTEGER CHECK (total_pages > 0),
    current_chapter INTEGER CHECK (current_chapter >= 0),
    review          TEXT,
    rating          NUMERIC(2, 1) NOT NULL DEFAULT 0
                    CHECK (rating BETWEEN 0 AND 5 AND rating * 2 = round(rating * 2)),
    genre           TEXT,
    is_favorite     BOOLEAN NOT NULL DEFAULT false,
    started_at      TIMESTAMPTZ,
    finished_at     TIMESTAMPTZ,
    last_read_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, work_id),
    CHECK (current_page <= total_pages)
);

CREATE TABLE likes (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    user_book_id INTEGER NOT NULL REFERENCES user_books (id) ON DELETE CASCADE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, user_book_id)
);

CREATE TABLE comments (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    user_book_id INTEGER NOT NULL REFERENCES user_books (id) ON DELETE CASCADE,
    text         TEXT NOT NULL CHECK (length(trim(text)) > 0),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ON editions (work_id);
CREATE INDEX ON user_books (work_id);
CREATE INDEX ON likes (user_book_id);
CREATE INDEX ON comments (user_book_id);