-- DEVELOPMENT ONLY: deletes the tables (and ALL their data) so this file can be run again.
DROP TABLE IF EXISTS user_book_tags, post_tags, tags, saved_posts, post_comments, post_likes, post_books, posts, comments, likes, user_books, editions, work_translations, works, users;

CREATE TABLE users(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        TEXT NOT NULL UNIQUE,
    email           TEXT NOT NULL UNIQUE,
    password_hash   TEXT NOT NULL,
    display_name    TEXT,
    bio             TEXT,
    about_me        TEXT,
    favorite_quote  TEXT,
    favorite_things TEXT,
    location        TEXT,
    avatar_url      TEXT,
    instagram_url   TEXT,
    tiktok_url      TEXT,
    reading_goal    SMALLINT CHECK (reading_goal BETWEEN 1 AND 365),
    reader_type     TEXT CHECK (reader_type IN ('first-time', 'casual', 'avid')),
    language        TEXT NOT NULL DEFAULT 'en' CHECK (language IN ('en', 'es')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now() 
);

CREATE TABLE works (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                TEXT NOT NULL,
    author               TEXT NOT NULL,
    description          TEXT,
    cover_image          TEXT,
    first_published_year SMALLINT,
    open_library_key     TEXT UNIQUE,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE work_translations (
    work_id     INTEGER NOT NULL REFERENCES works (id) ON DELETE CASCADE,
    language    TEXT NOT NULL CHECK (language IN ('en', 'es')),
    title       TEXT NOT NULL,
    description TEXT,
    PRIMARY KEY (work_id, language)
);

CREATE TABLE editions (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_id          INTEGER NOT NULL REFERENCES works (id) ON DELETE CASCADE,
    title            TEXT NOT NULL,
    language         TEXT,
    isbn_13          TEXT UNIQUE CHECK (isbn_13 ~ '^[0-9]{13}$'),
    publisher        TEXT,
    published_year   SMALLINT,
    page_count       SMALLINT CHECK (page_count > 0),
    cover_image      TEXT,
    open_library_key TEXT UNIQUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE user_books (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    work_id         INTEGER NOT NULL REFERENCES works (id) ON DELETE RESTRICT,
    edition_id      INTEGER REFERENCES editions (id) ON DELETE SET NULL,
    status          TEXT NOT NULL DEFAULT 'reading'
                    CHECK (status IN ('want-to-read', 'reading', 'finished')),
    progress        SMALLINT NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),
    current_page    INTEGER CHECK (current_page >= 0),
    total_pages     INTEGER CHECK (total_pages > 0),
    current_chapter INTEGER CHECK (current_chapter >= 0),
    review          TEXT,
    rating          NUMERIC(2, 1) NOT NULL DEFAULT 0
                    CHECK (rating BETWEEN 0 AND 5 AND rating * 2 = round(rating * 2)),
    genre           TEXT,
    is_favorite     BOOLEAN NOT NULL DEFAULT false,
    started_at      TIMESTAMPTZ,
    finished_at     TIMESTAMPTZ,
    last_read_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, work_id),
    CHECK (current_page <= total_pages)
);

CREATE TABLE likes (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    user_book_id INTEGER NOT NULL REFERENCES user_books (id) ON DELETE CASCADE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, user_book_id)
);

CREATE TABLE comments (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    user_book_id INTEGER NOT NULL REFERENCES user_books (id) ON DELETE CASCADE,
    text         TEXT NOT NULL CHECK (length(trim(text)) > 0),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE posts (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    text       TEXT CHECK (length(text) <= 2000),
    image_url  TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE post_books (
    post_id  INTEGER NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    work_id  INTEGER NOT NULL REFERENCES works (id) ON DELETE RESTRICT,
    position SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (post_id, work_id)
);

CREATE TABLE post_likes (
    user_id    INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    post_id    INTEGER NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, post_id)
);

CREATE TABLE post_comments (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    post_id    INTEGER NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    text       TEXT NOT NULL CHECK (length(trim(text)) > 0 AND length(text) <= 1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE saved_posts (
    user_id    INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    post_id    INTEGER NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, post_id)
);

CREATE TABLE tags (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL CHECK (length(name) BETWEEN 1 AND 40),
    slug       TEXT NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE post_tags (
    post_id  INTEGER NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    tag_id   INTEGER NOT NULL REFERENCES tags (id) ON DELETE CASCADE,
    position SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (post_id, tag_id)
);

CREATE TABLE user_book_tags (
    user_book_id INTEGER NOT NULL REFERENCES user_books (id) ON DELETE CASCADE,
    tag_id       INTEGER NOT NULL REFERENCES tags (id) ON DELETE CASCADE,
    position     SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (user_book_id, tag_id)
);

CREATE TABLE tag_follows (
    user_id    INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    tag_id     INTEGER NOT NULL REFERENCES tags (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, tag_id)
);

CREATE INDEX ON editions (work_id);
CREATE INDEX ON user_books (work_id);
CREATE INDEX ON likes (user_book_id);
CREATE INDEX ON comments (user_book_id);
CREATE INDEX posts_user_created_idx ON posts (user_id, created_at DESC);
CREATE INDEX posts_created_idx ON posts (created_at DESC);
CREATE INDEX post_books_work_idx ON post_books (work_id);
CREATE INDEX post_likes_post_idx ON post_likes (post_id);
CREATE INDEX post_comments_post_idx ON post_comments (post_id);
CREATE INDEX post_tags_tag_idx ON post_tags (tag_id);
CREATE INDEX user_book_tags_tag_idx ON user_book_tags (tag_id);
CREATE INDEX tag_follows_tag_idx ON tag_follows (tag_id);


ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE works ENABLE ROW LEVEL SECURITY;
ALTER TABLE editions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_books ENABLE ROW LEVEL SECURITY;
ALTER TABLE likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_translations ENABLE ROW LEVEL SECURITY;
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_books ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE saved_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_book_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE tag_follows ENABLE ROW LEVEL SECURITY;