CREATE TABLE IF NOT EXISTS tags (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL CHECK (length(name) BETWEEN 1 AND 40),
    slug        TEXT NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS post_tags (
    post_id     INTEGER NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    tag_id      INTEGER NOT NULL REFERENCES tags  (id) ON DELETE CASCADE,
    position    SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (post_id, tag_id)
);

CREATE TABLE IF NOT EXISTS user_book_tags (
    user_book_id INTEGER NOT NULL REFERENCES user_books (id) ON DELETE CASCADE,
    tag_id       INTEGER NOT NULL REFERENCES tags (id) ON DELETE CASCADE,
    position     SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (user_book_id, tag_id)
);

CREATE INDEX IF NOT EXISTS post_tags_tag_idx ON post_tags (tag_id);
CREATE INDEX IF NOT EXISTS user_book_tags_tag_idx ON user_book_tags (tag_id);

ALTER TABLE tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_book_tags ENABLE ROW LEVEL SECURITY;
